### ISSUE TITLE
[bug] Volume Create fails if Storage unit directory exists

### ISSUE THREAD

**Issue by aravindavk** [kadalu/moana#148]
If the Storage unit directory is pre created then Volume create fails.

- Create a user and login `kadalu user create admin` and `kadalu user login admin`
- Create the Storage unit directory `mkdir -p /exports/vol1/s1`
- Now create the Volume by running `kadalu volume create DEV/vol1 kadalu-dev:/exports/vol1/s1 --auto-create-pool --auto-add-nodes`

Volume create fails with the below error

```console
$ kadalu volume create DEV/vol1 kadalu-dev:/exports/vol1/s1 --auto-create-pool --auto-add-nodes
Failed to Create Volume
[HTTP Error: 400] Invalid Volume create request
  [051a57f8-dade-4a51-9bb4-9ed4fcaf9e48] Failed to create Storage unit path /exports/vol1/s1 (Error: Unable to create directory: '/exports/vol1/s1': File exists) (HTTP Error: 400)
```

Fix is required in two places one during the validation phase and other during the creation phase(Move the check to validation phase https://github.com/kadalu/moana/blob/main/mgr/src/server/plugins/volume_utils.cr#L133). Add new CLI option to reuse storage units(`--reuse-storage-units`)(Add this option to Volume create CLI and `MoanaTypes::Volume`. Similar to `no_start` option)

If the Storage unit directory exists then (https://github.com/kadalu/moana/blob/main/mgr/src/server/plugins/volume_utils.cr#L70)
    - try to get volume-id xattr from that path. If no xattr exists then it is good.
    - If xattr exists, compare with `req.id`
        - if same then good
        - Else if req.reuse_storage_units is set then overwrite the volume-id xattr with `req.id`
        - Else ERROR

**Note**: Make sure to delete the storage_unit path only if it is created during validation(not pre existing) https://github.com/kadalu/moana/blob/main/mgr/src/server/plugins/volume_utils.cr#L81

**Comment by vatsa287** [comment]
Here `req.id` is coming from CLI through `--volume-id` right? Since currently new volumes have no `req.id`.

**Comment by aravindavk** [comment]
> Here `req.id` is coming from CLI through `--volume-id` right? Since currently new volumes have no `req.id`.

Yes. Add `--volume-id` to CLI and set to `req.id`(CLI code)
