### ISSUE TITLE
[RFE] See if we can host a volfile provider service based on glusterd's volfile server code

### ISSUE THREAD

**Issue by amarts** [kadalu/moana#191]
It needs a glusterfs xlator itself be loaded as volfile server, thus helping all existing glusterfs clients to connect to servers started by moana servers.

This also helps an easier gfapi porting option for moana.

**Comment by aravindavk** [comment]
Related: https://github.com/kadalu/moana/issues/134

**Comment by aravindavk** [comment]
Based on the discussion in the last meeting:

* On Volume Start/Set/Reset, generate the Volfile in all the Brick/Storage units nodes of respective Volume.
* Mount script runs the glusterfs  process with all the brick/storage-unit nodes and port as `--volfile-server` argument.
* `glusterfsd` process (Brick/Storage Unit) process will support serving the Volfile.
* On Volume option change, Moana notifies the Brick/Storage unit process by sending `SIGHUP`. Embeded Volfile server in glusterfsd will notify the connected Clients(RPC).

**Comment by aravindavk** [comment]
Fixed via https://github.com/kadalu/moana/pull/238 and https://github.com/kadalu/moana/pull/240
