### ISSUE TITLE
Consistency in volume/node/pool commands 

### ISSUE THREAD

**Issue by sac** [kadalu/moana#204]
To delete a volume
```# kadalu volume delete ...```

To delete a pool
```# kadalu pool delete ...```

To delete a node, however, the command is
```# kadalu node remove ...```

We should follow a consistent naming. If the fix is straightforward we should go for this fix before 1.0

**Comment by aravindavk** [comment]
This is because Node is added to the Pool. Create may give wrong impression. So `remove` is used (`add/remove`). Pool and Volumes are created and deleted. 

Will it makes sense to use `node create` and `node delete` instead of `node add` and `node remove`?

**Comment by sac** [comment]
Now looking from your point of view it looks reasonable.
As an end user, I tend to use delete consistently and find it easy to script the cleanup. 
We can defer this issue for now. And see how the majority of users respond.

**Comment by aravindavk** [comment]
We can have command alias so that `node add` and `node create` both works (Similarly `node remove` and `node delete`)
