### ISSUE TITLE
In the usage message of kadalu node list, pool name is empty

### ISSUE THREAD

**Issue by sac** [kadalu/moana#205]
```
# kadalu node list 
No nodes added to the Pool. Run `kadalu node add /<node-name>` to add a node.
```

Since the pool name is not provided in the CLI the usage message throws an empty pool name.

**Comment by sac** [comment]
Created https://github.com/kadalu/moana/pull/206 please review if the fix is acceptable.

**Comment by aravindavk** [comment]
Fixed via https://github.com/kadalu/moana/commit/2a179911b23e947035f55360a9b27ac281046045
