### ISSUE TITLE
Debian/Ubuntu Packaging

### ISSUE THREAD

**Issue by aravindavk** [kadalu/moana#215]
Packaging Moana also requires GlusterFS packages. Following packages are required.

* <strike>`kadalu-storage-cli` - Moana binary, Mount script</strike>
* `kadalu-storage-manager` - Moana <strike>Service file and Depends on `kadalu-storage-cli`</strike>
* `kadalu-storage-server` - GlusterFS server without Glusterd (Use `--disable-glusterd` while building). Depends on `kadalu-storage-manager`, `kadalu-storage-client`, `kadalu-storage-api`
* `kadalu-storage-client` - GlusterFS Client. Depends on <strike>`kadalu-storage-cli`</strike>`kadalu-storage-manager`
* `kadalu-storage-api` - GFAPI bindings (May be after 1.0)
* `python3-kadalu-storage` - clients/python

## Install
* Users who only wants to Setup Kadalu Storage Server will install using `apt install kadalu-storage-server`
* Users who only wants to setup a Client machine will install using `apt install kadalu-storage-client`
* To use Python bindings from a remote machine, `apt install python3-kadalu-storage`
* To use Kadalu CLI without installing Client/Server, `apt install kadalu-storage-manager`
* To setup only the Storage manager that will not be a Storage node: `apt install kadalu-storage-manager`

**Comment by aravindavk** [comment]
@sac @amarts ^^

**Comment by amarts** [comment]
Lets clearly say which is the source repo (and version/git commit id) for `kadalu-storage-server`. Other than that, things look good.

**Comment by sac** [comment]
Looks good. Wondering if we can merge some of them. Too many packages are a little overwhelming. But still okay with that.

**Comment by vatsa287** [comment]
Can this be closed?

**Comment by shvetsnikita** [comment]
> Can this be closed?

Maybe before closing this report it's good idea to start publishing debs on Release page or, even better, provide repository?

**Comment by aravindavk** [comment]
> > Can this be closed?
> 
> Maybe before closing this report it's good idea to start publishing debs on Release page or, even better, provide repository?

Yeah. Package details available here: https://kadalu.tech/storage/quick-start/

Packages build scripts are available in the repo: https://github.com/kadalu-tech/pkgs

**Comment by shvetsnikita** [comment]
> Package details available here: https://kadalu.tech/storage/quick-start/

Indeed, thanks! Any reason why it's not mentioned in [Install section of Kadalu documentation](https://docs.kadalu.tech/kadalu-storage/latest/install/)?

**Comment by aravindavk** [comment]
> > Package details available here: https://kadalu.tech/storage/quick-start/
> 
> Indeed, thanks! Any reason why it's not mentioned in [Install section of Kadalu documentation](https://docs.kadalu.tech/kadalu-storage/latest/install/)?

Thanks for pointing out. We will update the doc.

Are you using Kadalu Storage as GlusterFS replacement or with Kubernetes?

**Comment by shvetsnikita** [comment]
> Are you using Kadalu Storage as GlusterFS replacement or with Kubernetes?

I planning to make test deployment on k3s. Hopefully this month, if all necessary parts will arrive in time.

**Comment by aravindavk** [comment]
> > Are you using Kadalu Storage as GlusterFS replacement or with Kubernetes?
> 
> I planning to make test deployment on k3s. Hopefully this month, if all necessary parts will arrive in time.

Please refer this doc (https://docs.kadalu.tech/k8s-storage/latest/) to use Kadalu Storage with Kubernetes/k3s. 

Above doc(https://docs.kadalu.tech/kadalu-storage/latest/) is for standalone deployments(Non K8s)

**Comment by shvetsnikita** [comment]
> Please refer this doc (https://docs.kadalu.tech/k8s-storage/latest/) to use Kadalu Storage with Kubernetes/k3s.

Pardon my ignorance, but is Moana even suitable for managing this type of Kadalu deployment? I just assumed [same scenario](https://rook.io/docs/rook/v1.12/Storage-Configuration/Monitoring/ceph-dashboard/) is possible with Kadalu, but it's seems like I mistake.

**Comment by aravindavk** [comment]
> > Please refer this doc (https://docs.kadalu.tech/k8s-storage/latest/) to use Kadalu Storage with Kubernetes/k3s.
> 
> Pardon my ignorance, but is Moana even suitable for managing this type of Kadalu deployment? I just assumed [same scenario](https://rook.io/docs/rook/v1.12/Storage-Configuration/Monitoring/ceph-dashboard/) is possible with Kadalu, but it's seems like I mistake.

Many management operations done by Moana may not be required/redundant  in K8s. For example, cluster management, health check etc. Kadalu K8s integration is very light weight and doesn't use any management layer from Gluster/Kadalu Storage. It directly integrated with the K8s APIs.
