### ISSUE TITLE
mgr[Bug]: Node deletion does not happen after volume has been transferred to new pool

### ISSUE THREAD

**Issue by vatsa287** [kadalu/moana#250]
The `.info/` file contains `pool_name` which is set to old pool.
Fix: After every successful volume transfer to new pool. Update the `pool_name` details in `.info` by sending a node_action to every participating nodes.

**Comment by aravindavk** [comment]
Is this fixed in the above PR?

**Comment by vatsa287** [comment]
Yes I think it has been resolved with https://github.com/kadalu/moana/pull/237/ and tests have been added too.
