### ISSUE TITLE
fix-layout: The fix-layout process is stuck/running even after the dir creation is complete.

### ISSUE THREAD

**Issue by vatsa287** [kadalu/moana#288]
fix-layout: The fix-layout process is stuck/running even after the dir creation is complete.

Expectation:
The fix-layout process should exit after fixing the layout in the expanded brick.

But, 
the process is still runs even after writing the status file stating the fix-layout progress is completed.

**Comment by aravindavk** [comment]
I tried to reproduce this. Process is exiting after the run. I see stale mount process (`glusterfs` process) but no `kadalu _rebalance` process.
