### ISSUE TITLE
arm64 downloads missing

### ISSUE THREAD

**Issue by javierin** [kadalu/moana#292]
Hi

I am trying to setup kadalu on a bunch of OrangePi5 but arm64 is unavailable at the downloads page. Only amd64 is there. I have found no previous reference to this in closed issues.

> root@orangepi01:~# curl -fsSL https://github.com/kadalu/moana/releases/latest/download/install.sh | bash -x
> ++ uname -m
> ++ sed 's|aarch64|arm64|'
> ++ sed 's|x86_64|amd64|'
> + curl -fsSL https://github.com/kadalu/moana/releases/latest/download/kadalu-arm64 -o /tmp/kadalu
> curl: (22) The requested URL returned error: 404

Manually browsing to the [downloads page](https://github.com/kadalu/moana/releases/tag/1.0.0) also confirmed arm64 was not there

Would it be possible to have this version available or a clarification on how to generate it?
Thanks

**Comment by aravindavk** [comment]
Release CI for Arm64 is broken. I will fix it. 

If the OS is Ubuntu 22.04 then you can try installing Kadalu Storage using `apt` (https://kadalu.tech/storage/quick-start/)

**Comment by javierin** [comment]
Thanks for your feedback. I am using debian 11, so I will wait until the build is fixed again

Kind regards
