### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by aravindavk** [kadalu/moana#59]
Since the Manager instance is running in a single node, backup of configuration data is very important to avoid the single point of failure.

The manager itself can call backup command on every change to the Pool or on a periodic interval. (To be implemented later as a separate issue)

```console
$ kadalu backup --backup-dir=/data/backups
Backup created successfully!
Backup file: /data/backups/kadalu_202204111307.tar.gz
```

```console
$ kadalu restore /data/backups/kadalu_202204111307.tar.gz
Overwrite any existing Db? Y
Restored from the backup successfully!
```

Expose a functions `Datastore.backup(target_path)` and `Datastore.restore(backup_path)`

Backup:

- Create a backup dir with name "kadalu_<timestamp>"
- Copy `/var/lib/kadalu/info` file(If exists) to `$BACKUP_TARGET_DIR/info`
- Take dump of Db to `$BACKUP_TARGET_DIR`
- Create `tar.gz` and remove the Backup target dir

Db Dump Example

```crystal
backup_conn = DB.open("sqlite3://#{backup_dir}/kadalu_<timestamp>.db").as(SQLite3::Connection)
Datastore.connection.as(SQLite3::Connection).dump(backup_conn)
```

Restore:

- Stop the Mgr process if running.
- Create `mgr` file under `/var/lib/kadalu`
- Restore the Db(Reverse dump) to `/var/lib/kadalu/meta/kadalu.db` (Confirm Overwrite if Db file exists)
- Copy the info file back to `/var/lib/kadalu`
- Start the Mgr

*Note*: Backup and Restore commands are only local commands. Cannot be initiated from other nodes. Even if it is initiated from other nodes, backup file will be created in the Mgr node itself.

**Comment by vatsa287** [comment]
In `restore` how to get the confirmation from user on overwriting existing `kadalu.db` file? Since the operations will be sent on API to `server`. Should it take place in `/cmd` itself or call the API again on confirmation? @aravindavk

**Comment by aravindavk** [comment]
> In `restore` how to get the confirmation from user on overwriting existing `kadalu.db` file? Since the operations will be sent on API to `server`. Should it take place in `/cmd` itself or call the API again on confirmation? @aravindavk 

Confirmation is only for CLI. Refer volume stop/delete command.
