### ISSUE TITLE
Volume Create

### ISSUE THREAD

**Issue by aravindavk** [kadalu/moana#74]
Two variants

1)

```
kadalu volume create <cluster_name>/<volume-name> \
    [replica <count>|disperse <count> redundancy <count>]
    storage_unit1 storage_unit2...
```

Storage unit in the form of `<host>:<path>` or `<host>:<device>`

Example: (Replica 3 Volume)

```
kadalu volume create mycluster/myvol \
    replica 3 \
    node1.example.com:/exports/myvol/s1 node2.example.com:/exports/myvol/s2 node3.example.com:/exports/myvol/s3
```

2)

```
kadalu volume create <cluster_name>/<volume-name> \
    [replica storage_unit1 storage_unit2... | disperse storage_unit1,storage_unit2.. redundancy storage_unit3..]
```

Example: (Replica 3 Volume)

```
kadalu volume create mycluster/myvol \
    replica node1.example.com:/exports/myvol/s1 node2.example.com:/exports/myvol/s2 node3.example.com:/exports/myvol/s3
```

- Add support for `mirror` alias for `replica`
- Save the Volume create request in the Volume so that a few customizations are possible while showing the Volume info/status(Example: Show `Mirrored` instead of `Replicate` if mirror was used in create command)

Other flags required are:

- `--brick-fs=xfs|ext4|zfs` This is useful when storage unit is provided as `<host>:<device>`
- `--fs-opts=<opts>` To use with `mkfs`
- `--use-lvm` To use Thin Volume to use LVM Snapshot feature. Not applicable for `zfs`
- `--allow-rootdirs` To allow creating Storage units in the Root directories.
- `--no-start` Do not start the Volume automatically after create.

A few more options required in this command. I will add the list of flags in comments or create a new issue.

**Comment by aravindavk** [comment]
<strike>Add support for Auto Volume name.</strike> 

This can be handled in external application. Not much use to have in core.

```
kadalu volume create \
    --auto-volume-name
    replica node1.example.com:/exports/myvol/s1 \
            node2.example.com:/exports/myvol/s2 \
            node3.example.com:/exports/myvol/s3
```

**Comment by aravindavk** [comment]
Add support for Volume ID reuse(Re-create a deleted Volume)

```
kadalu volume create mycluster/myvol \
    replica node1.example.com:/exports/myvol/s1 \
            node2.example.com:/exports/myvol/s2 \
            node3.example.com:/exports/myvol/s3
    --volume-id 77400e87-a361-456d-aa32-6c9fdd393d29
```

**Comment by amarts** [comment]
> Add support for Volume ID reuse(Re-create a deleted Volume)

Or to the support of migrating from existing setup.
