### ISSUE TITLE
Snapshot Clone

### ISSUE THREAD

**Issue by aravindavk** [kadalu/moana#83]
```
kadalu snapshot clone <volname>@<snapname> <clonename>
```

**Comment by aravindavk** [comment]
Snapshot Clone is not so useful in Gluster/Kadalu Storage since all the backend storage units share the same space. Please reopen this if this feature is required.

**Comment by leelavg** [comment]
@aravindavk there's one CSI RPC wherein user wants to create a PVC from Snapshot of another PVC (CLONE_VOLUME).

If there are no other ways to fulfill the request this issue might be worth considering 🤔

**Comment by aravindavk** [comment]
Snapshot here is taking full volume snapshot (Storage Pool snapshot in Kadalu+k8s). Snapshot in Gluster or Kadalu Storage is implemented using the backend filesystem snapshot feature(LVM Snapshot for XFS/ext4, ZFS Snapshot). Snapshot clone is basically creating a Snapshot and making it writable. It is not scalable since original volume and cloned volumes shares the same backend volume.

Also full volume Snapshot is not so useful for PV Snapshots. Blocking all Apps IO while taking one PV Snap doesn't makes sense also each PV snapshot frequency may be different.

Copy data from template PV when a new PV to be created(CLONE_VOLUME).
